export const siteConfig = {
  siteVersion: `1.0.5`,
  title: `Yash Godara`,
  aboutMe: ``,
  creator: `Yash Godara`,
  publisher: `Yash Godara`,
  category: `technology`,
  authors: [
    {
      name: `Yash Godara`,
      twitterHandle: `@y17godara`,
      url: `https://www.y-g.tech`,
    },
  ],
  description: `Hello, My Name is Yash Godara (@y17godara) and I am a Developer and Design Enthusiast From New Delhi, India.`,
  twitterHandle: `@y17godara`,
  meta: `Developer Expertise in Tech like ▲ Next.js, TailwindCSS, React, TypeScript, Node.js, Serverless, Prisma PostgreSQL, MongoDB, and more. Aspiring to become a successful software and web developer.`,
  url: `${process.env.NEXT_PUBLIC_BASE_URL}` || `https://www.y-g.tech`,
  generator: `Next.js`,
  ogImage: `https://www.y-g.tech/opengraph-image.png`,
  links: {
    twitter: "https://x.com/y17godara",
    github: "https://github.com/y17godara",
    linkedin: "https://www.linkedin.com/in/y17godara",
  },
  keywords: [
    "Yash Godara y17godara",
    "y17godar",
    "Yash Github",
    "Yash Godara",
    "Yash Portfolio Website",
    "Yash Blogs Website",
    "Yash Personal Website",
    "Yash Godara Website",
    "Yash Godara Portfolio",
    "Yash Godara Blogs",
    "Yash Godara Personal Website",
    "Yash Godara Github",
    "Github y17godara",
    "y-g.tech",
    "Yash Godara y-g.tech",
    "y17godara y-g.tech",
    "Yash Godara Portfolio Website y-g.tech",
  ],
};

export type SiteConfig = typeof siteConfig;
